/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 27038e371a042400988f9903d82e649b)
interface __BaseEnv_Env {
	DB: D1Database;
	CADENCIA_ENABLE_LIVE: string;
	CADENCIA_INTENT_SERVICE_URL: string;
	CADENCIA_SERVICE_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CADENCIA_ENABLE_LIVE" | "CADENCIA_INTENT_SERVICE_URL" | "CADENCIA_SERVICE_TOKEN">> {}
}
