/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: be4df24a726174f1b2328d687cf14be9)
interface __BaseEnv_Env {
	CADENCIA_ENABLE_LIVE: string;
	CADENCIA_INTENT_SERVICE_URL: string;
	CADENCIA_SERVICE_TOKEN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CADENCIA_ENABLE_LIVE" | "CADENCIA_INTENT_SERVICE_URL" | "CADENCIA_SERVICE_TOKEN">> {}
}
